### ISSUE TITLE
Error message about Cholesky factorization of covariance matrix

### ISSUE THREAD

**Issue by lpswiler** [libqueso/queso#203]
We have been seeing an error message while running QUESO.  I seem to remember that Ernesto said this wasn't really an error, but it is disconcerting, especially since we are giving QUESO proposal covariances that are positive definite.

This is the error message: 
In GslMatrix::chol(): iRC = 1, gsl error message = input domain error 
UQ RC ERROR, rank 0, in GslMatrix::chol(): matrix is not positive definite, iRc = 1 In 
MetropolisHastingsSG<P_V,P_M>::generateFullChain(): first chol failed

We would like to ensure this is not a true error and fix it in some way to remove the error message.

Thank you, 
Laura Swiler (Sandia Labs)

**Comment by briadam** [comment]
@dmcdougall, @lpswiler  I will try to generate a small example that doesn't require a Dakota driver.  This is again our friend the cantilever beam, with one parameter order unity and another 1e7.  

It looks to me like the initial proposal covariance factors fine, but then after 3 or 4 chain samples (depending on initial covariance), the Cholesky "fails" on the adapted proposal covariance.  It appears that there's recourse via regularization in MetropolicHastingsSG::generateFullChain(), around line 2200, though I don't see the diagonal multiplier ever get used. Perhaps the initial factorization is failing and then life is good after adding diagonal weight.

Perhaps "failed" is just too strong a word to use in the output?

**Comment by briadam** [comment]
@dmcdougall I was able to create a simple version of the Rosenbrock problem that demonstrates this error.  I created this branch: https://github.com/briadam/queso/tree/chol_error_203, with one modified test file (SHA: 4d8bb057ea53835ad533c8981f496b6e08eecdbe).  The following steps:
```
cd build/test
make test_LlhdTargetOutput
./test_LlhdTargetOutput test_StatisticalInverseProblem/llhdout_input.txt
```
Will yield:
```
In GslMatrix::chol(): iRC = 1, gsl error message = input domain error
Here is the offending matrix: 
0.111429 -0.265435 ; -0.265435 nan 
UQ RC ERROR, rank 0, in GslMatrix::chol(): matrix is not positive definite, iRc = 1
In MetropolisHastingsSG<P_V,P_M>::generateFullChain(): first chol failed
```

If the adapted proposal should remain valid for these adaptation settings, perhaps there is a bug.  If not and the recourse is expected, could we change the "error" to a warning?

**Comment by dmcdougall** [comment]
Thanks.  I'll look into this.

**Comment by dmcdougall** [comment]
@briadam I just ran the modified test file and I did not get the error reported by gsl (with or without logit transform).  Can you confirm you are linking against v0.52.0?

**Comment by briadam** [comment]
No, not v0.52.0, my branch was off dev.  let me do a clean clone and build and see if I can reproduce it still.  Sorry for the thrash.

**Comment by dmcdougall** [comment]
We just released v0.52.0, and I think the only changes to `dev` since then were to update an entry in `CHANGES` that I forgot about.  I'll try again with dev just to make sure though.  Thanks for clarifying.

**Comment by briadam** [comment]
I can't reproduce in a clean tree either.  Ugh.  Will keep you posted.

**Comment by dmcdougall** [comment]
Fiddlesticks.

Thanks for your time and effort on this, and sorry for the runaround.

**Comment by briadam** [comment]
I figured it out.  I had edited a file in my build tree, but didn't update the source tree. I updated my branch with the input file modification.  If you set ip_mh_am_initialNonAdaptInterval = 1 (or =2) you can cause the chol error to manifest itself.  I realize from our previous discussion this may be a silly value of this parameter, but perhaps it gives you a test case from which you can debug why the adapted proposal covariance is not positive definite.

**Comment by dmcdougall** [comment]
I can confirm this now.  Thanks for the tip.

Hopefully now we have a recreate we can get to the bottom of this.  It is my understanding that the adaptivity should always remain positive definite, but this could be wrong.  I'll review the Haario paper again to re-confirm.

Note:  I also get a recreate with the logit transform logic *off*, meaning it's unlikely that this is a problem with the transform logic.

**Comment by briadam** [comment]
Yes, I also saw that the Logit transform didn't matter.

**Comment by mseldre** [comment]
Damon,
We are now passing +/- infinity as the parameter bounds for unbounded priors, and the logit transform appears to be working properly (subtle effect on results for bounded priors and no effect for unbounded priors).  We still see the Cholesky problem whenever adaptive Metropolis is on, but it appears unrelated to logit.  If we can get this last problem sorted out (including the related issue of appropriate specifications for adaptive Metropolis), then I think we're go to go for our upcoming release.
Thanks,
--Mike

**Comment by dmcdougall** [comment]
I've had time to look into this more.

I'll summarise first.  The fix here, I think, is to improve the error message that is printed to inform the user what is happening.  I believe QUESO is behaving in a sensible manner regarding adaptation.

Now for the explanation of what is happening.  The user can provide various options that influence the computation of the adapted proposal covariance matrix.  First, the option `m_amInitialNonAdaptInterval` specifies the length of the initial period during which no adaptivity is done.  Once this period has passed, QUESO will attempt to adapt every `m_amAdaptInterval` samples.  Let us assume that we are at a point the in chain where it is time for QUESO to adapt the proposal covariance matrix.  First, QUESO will computed the new proposal covariance matrix using the sample covariance update formula found in Haario et al (2006) **without** the added \epsilon I regularisation term.

The sample covariance matrix is not guaranteed to be positive definite.  One can improve stability and computation time by implementing an algorithm that acts only on the Cholesky factor of the proposal covariance matrix, but this does not address the problem that some samples might give you a sample covariance matrix that is ill-conditioned or even singular.  For example, a sample covariance matrix from three samples in a 1000 dimensional space will probably behave poorly.  So, the first thing that QUESO does is check if the newly computed proposal covariance matrix is positive definite by attempting to do a Cholesky factorisation.  This is expensive, I agree.  I will come back to this later.

If the Cholesky factorisation succeeds, you will not see the printed message above, and QUESO will use the newly computed proposal covariance matrix for the next `m_amAdaptInterval` samples.

If the Cholesky factorisation fails QUESO prints the error message @lpswiler and @briadam mentioned above.  QUESO then tries to fix it by adding the \epsilon I regularisation term found in Haario et al. (2006) to the computed proposal covariance matrix.  The \epsilon parameter is determined by the input file option `amEpsilon`.  We then test if the **regularised** proposal covariance matrix is positive definite.  This is also done by attempting to do a Cholesky factorisation.  This is expensive, I know.  I will come back to this later.

If the (second) attempted Cholesky factorisation succeeds for the regularised proposal covariance matrix, QUESO will use it for the next `m_amAdaptInterval` samples.

If the (second) attempted Cholesky factorisation fails for the regularised proposal covariance matrix, QUESO's fallback behaviour is the use the previous proposal covariance matrix.  Note that if the procedure above hasn't executed before, then the previous proposal covariance matrix will be the user provided initial proposal covariance matrix for the next `m_amAdaptInterval` samples..

The above procedure is repeated.

So the message you see is not a fatal error, and the fact that you don't see a message regarding a failure for the **regularised** proposal covariance matrix implies the `m_amEpsilon` parameter is large enough that you end up with a useful and factorisable matrix after regularisation.  That said, the message you see could be phrased a little better to explain what is going on, and I'm about to open a pull request that does exactly that (and a few other code cleanups in that area of QUESO).

Now, as I mentioned above, we're doing **two** attempted Cholesky factorisations each time we try to adapt assuming the first factorisation failed.  This is especially wasteful and will result in a nontrivial performance penalty for large dimensional problems.  A much better approach, in my opinion, is to store the Cholesky factorisation and only update the Cholesky factor when it is time to adapt.  These sorts of algorithms tend to not have the floating point issues of update formulas on the full matrix.  That said, it doesn't fix the problem for the case where you were just unlucky or you didn't wait long enough.  It will, however, have the benefit of being more computationally efficient.

**Comment by dmcdougall** [comment]
#382 was merged.

@briadam, @lpswiler or @mseldre Please feel free to re-open if #382 is not a reasonable solution.
